### ISSUE TITLE
net::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by mmailaender** [liuweiGL/vite-plugin-mkcert#101]
### Describe the bug

After installing vite-plugin-mkcert and configuring it in my vite.config.ts as part of my svelte kit project:

```
import { paraglide } from '@inlang/paraglide-sveltekit/vite';
import { defineConfig } from 'vitest/config';
import { sveltekit } from '@sveltejs/kit/vite';
import mkcert from'vite-plugin-mkcert'

export default defineConfig({
	plugins: [
		mkcert(),
		sveltekit(),
		paraglide({
			project: './project.inlang',
			outdir: './src/lib/paraglide'
		})
	],

	test: {
		include: ['src/**/*.{test,spec}.{js,ts}']
	}
});
```
the server starts as https, and I can also access it, but the certificate is not trusted.

![image](https://github.com/user-attachments/assets/7eb1071c-be9d-4f47-8d64-110dccf31469)

Do I have missed something to make it also trusted?

### System Info

Output of `npx envinfo --system --npmPackages vite,vite-plugin-mkcert --binaries --browsers`:

```node

  System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (20) x64 Intel(R) Core(TM) i5-14600
    Memory: 20.56 GB / 31.23 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 22.12.0 - /run/user/1000/fnm_multishells/357403_1734179495269/bin/node
    npm: 10.9.0 - /run/user/1000/fnm_multishells/357403_1734179495269/bin/npm
    pnpm: 9.15.0 - /run/user/1000/fnm_multishells/357403_1734179495269/bin/pnpm
  npmPackages:
    vite: ^6.0.3 => 6.0.3 
    vite-plugin-mkcert: ^1.17.6 => 1.17.6 
```

Used package manager: pnpm

**Comment by liuweiGL** [comment]
Perhaps there is a transition layer between vite and svelte kit, so vite-plugin-mkcert may not be working. I'm not a svelte user and I'm sorry I can't help you

**Comment by liuweiGL** [comment]
Maybe you can try putting `mkcert()` at the end of plugins

**Comment by mmailaender** [comment]
Thanks for the tip, but it seems not making any difference 🥲

**Comment by liuweiGL** [comment]
This scenario must be handled manually because the plug-ins cannot install ca certificates across systems

**Comment by mmailaender** [comment]
Maybe you can add a section to your readme to help people if they are using WSL? :) @liuweiGL

**Comment by danciudev** [comment]
This need to be in the readme

**Comment by danciudev** [comment]
Easy solution:

1. Add the plugin to vite.config.ts
2. Execute `vite dev` to generate the certificate files automatically after the dev server start
3. Execute this bash command in WSL
```bash
certutil.exe -user -addstore root "$(wslpath -w "$HOME/.vite-plugin-mkcert/rootCA.pem")"
```
Now your WSLcertificate is connected with windows
