### ISSUE TITLE
Failing under Widnows

### ISSUE THREAD

**Issue by AgainPsychoX** [liuweiGL/vite-plugin-mkcert#15]
### Describe the bug

Under Windows, installing the certs fail. In order to access `C:\Program Files\*` admin privileges are required. On the other hand, why would it install 

### Reproduction

1. Use the plugin under Windows without admin

### System Info

Output of `npx envinfo --system --npmPackages vite,@vitejs/plugin-vue --binaries --browsers`:

```node
  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.81 GB / 15.85 GB
  Binaries:
    Node: 16.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.84)
    Internet Explorer: 11.0.19041.1
```

Used package manager: `npm`

### Logs 

First time error (without `vite --debug` flag but still)
```node
error when starting dev server:
Created a new local CA 💥
The local CA is now installed in the system trust store! ⚡️
Note: Firefox support is not available on your platform. ℹ️
ERROR: failed to execute "keytool -importcert": exit status 1

Certificate was added to keystore
keytool error: java.io.FileNotFoundException: C:\Program Files\Java\jdk1.8.0_211\jre\lib\security\cacerts (Odmowa dost�pu)

    at ChildProcess.exithandler (node:child_process:326:12)
    at ChildProcess.emit (node:events:394:28)
    at ChildProcess.emit (node:domain:470:12)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

Second try error:
```node
  vite:config bundled config file loaded in 238ms +0ms
  vite:plugin:mkcert The hosts changed from [undefined] to [localhost,192.168.55.6,127.0.0.1], start regenerate certificate +0ms
error when starting dev server:
Error: Command failed: C:\Users\PsychoX\.vite-plugin-mkcert\mkcert.exe -install -key-file C:\Users\PsychoX\.vite-plugin-mkcert\certs\dev.key -cert-file C:\Users\PsychoX\.vite-plugin-mkcert\certs\dev.pem localhost 192.168.55.6 127.0.0.1
The local CA is already installed in the system trust store! 👍
Note: Firefox support is not available on your platform. ℹ️
ERROR: failed to execute "keytool -importcert": exit status 1

Certificate was added to keystore
keytool error: java.io.FileNotFoundException: C:\Program Files\Java\jdk1.8.0_211\jre\lib\security\cacerts (Odmowa dost�pu)


    at ChildProcess.exithandler (node:child_process:326:12)
    at ChildProcess.emit (node:events:394:28)
    at ChildProcess.emit (node:domain:470:12)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

---

**Comment by AgainPsychoX** [comment]
After a bit of investigation, I realized its `mkcert` the admin rights. If it's called only on (re)generating the certs - so, once or rarely - I think the plugin should just start it as elevated process.

Powershell could be used to run process elevated:
```js
util.promisify(child_process.exec)(`Start-Process cmd -Verb RunAs -Wait -ArgumentList '/c cd ${process.cwd()} && cmd'`, {shell: 'powershell.exe'})
.then(x => console.log(x)) // supports waiting for finish too
```

* If user was not elevated, the UAC dialog appears. If user agrees to elevate, the process run. On disagree, exception is fired. 
* If user was already elevated, there is no dialog, everything runs smoothly.
* There is small issue with this solution: additional terminal window will appear for a time the elevated process is running (but it's better than not working at all).

**Comment by liuweiGL** [comment]
>keytool error: java.io.FileNotFoundException: C:\Program Files\Java\jdk1.8.0_211\jre\lib\security\cacerts (Odmowa dost�pu)
Please try again after remove jdk environment setting.

**Comment by liuweiGL** [comment]
I don't see any logs related to the permission problem.

**Comment by AgainPsychoX** [comment]
Yeah, that works too:

```
cross-env JAVA_HOME= vite
```

Shouldn't it be added when using the binary then? Like:
```js

```

**Comment by AgainPsychoX** [comment]
@liuweiGL Can hiding `JAVA_HOME` be added if its running on Windows? 
`utils.ts`, around like 62:
```ts
export const exec = async (cmd: string) => {
  if (process.platform === 'win32') {
    const env = Object.assign({}, process.env)
    env.JAVA_HOME = ''
    return await util.promisify(child_process.exec)(cmd, {env})
  }
  else {
    return await util.promisify(child_process.exec)(cmd)
  }
}
```
If you can add that it would be nice. _(I can't use PNPM anyway so I can't do it myself)_

**Comment by liuweiGL** [comment]
I am sorry, i hope the plugin sticks to its responsibilities and keeps it simple and clean.

**Comment by AgainPsychoX** [comment]
So I should unset `JAVA_HOME` for whole building process? It's so messy...

**Comment by liuweiGL** [comment]
Remove `JAVA_HOME/bin`  from  path enviroment.

**Comment by liuweiGL** [comment]
`JAVA_HOME` environment variable is no effect.

**Comment by liuweiGL** [comment]
You are right, we don't need [support install into java cacerts file](https://github.com/FiloSottile/mkcert/pull/38).

I will take your advice, thank you.
