### ISSUE TITLE
Plugin does not work when running from inside docker

### ISSUE THREAD

**Issue by jonseppanen** [liuweiGL/vite-plugin-mkcert#22]
When running a vite project from inside docker, the certificate is invalid.
Attempting to import the certificate into chrome results in "Not an Authority".

**Comment by jonseppanen** [comment]
No errors in vite output log, everything works fine. Problem is the cert is generated and installed on the docker container machine, not the host machine which is browsing to the docker container.

Not sure how you would automate fixing that.

**Comment by liuweiGL** [comment]
Thanks for your feedbak, i will try to install docker on my own computer for testing.

**Comment by liuweiGL** [comment]
Nodejs can not access host’s home directory in docker, maybe you should use "docker mkcert" instead.
