### ISSUE TITLE
npm run start error

### ISSUE THREAD

**Issue by Candane** [liuweiGL/vite-plugin-mkcert#26]
![image](https://user-images.githubusercontent.com/23361322/165900349-69789499-e5aa-4cc9-a7da-51a61b0e7564.png)

**Comment by Candane** [comment]
> 没看到有跟插件相关的报错啊？

我也奇怪，不知道是不是哪里冲突了，我一把plugins的插件删了就能启动了，但是一加上就又跑不起来了，会一直在debugger状态，然后跑不起来

**Comment by liuweiGL** [comment]
是不是你的网络无法正常访问 github 服务？你可以尝试使用镜像下载。
