### ISSUE TITLE
if both preview and server are specifeid, only one of them will work.

### ISSUE THREAD

**Issue by azuruce** [liuweiGL/vite-plugin-mkcert#27]
some sort of cert issue.

**Comment by azuruce** [comment]
fixed in https://github.com/liuweiGL/vite-plugin-mkcert/pull/28

**Comment by liuweiGL** [comment]
https://github.com/liuweiGL/vite-plugin-mkcert/commit/bdbd92aeea912979b193b08b10fe7d555c288409
