### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by LucasBois1** [liuweiGL/vite-plugin-mkcert#34]
### Runtime Error

In v1.7.1 im getting a few of this runtime errors

![image](https://user-images.githubusercontent.com/44686060/172415960-5cef1e3d-de22-48e8-b5cf-0faecb589d93.png)

-------

I've modified this lines ...

(Lines 220, 281, 319)
(I've deleted all the '?' before the dots in those lines)

![image](https://user-images.githubusercontent.com/44686060/172416716-1048e1c2-07a3-4515-a577-d5bbd3b4f770.png)

![image](https://user-images.githubusercontent.com/44686060/172416649-b688fc29-2bef-4287-8947-1ba6de397131.png)

![image](https://user-images.githubusercontent.com/44686060/172416578-a0c1ccbf-1a15-4c01-98d0-a579a818b2db.png)

and now is up and running.

Since i modified the dist file and i dont know how to fix the source code, I've oppened this Issue and not made a Pull Request.

**Comment by liuweiGL** [comment]
Which version of  nodejs?

**Comment by LucasBois1** [comment]
Node version - v16.15.1 
npm version - v8.11.0
NVM version - v1.1.9

**Comment by liuweiGL** [comment]
What a weird bug, [optional chaining](https://cri.dev/posts/2020-05-01-Optional-chaining-in-Node.js-14/) is already supported in Node.js 14.

**Comment by liuweiGL** [comment]
You can append `console.log(process.version)` to `vite.config.js` to confirm the real node version.

**Comment by liuweiGL** [comment]
https://github.com/npm/cli/issues/4234#issuecomment-1040528646
