### ISSUE TITLE
mkcert is Incompatible with vite 3.1.0

### ISSUE THREAD

**Issue by smoya-ekoo** [liuweiGL/vite-plugin-mkcert#43]
after upgrade vite to 3.1.0 this throw the following error

Type 'Plugin_2' is not assignable to type 'PluginOption'.

![image](https://user-images.githubusercontent.com/112122665/188689812-78fceca1-ff9f-454e-be5b-bf0f1b44cc93.png)

Please upgrade to support new version of vite 
Thanks

**Comment by liuweiGL** [comment]
Which version of the `vite-plugin-mkcert` are you using?

**Comment by smoya-ekoo** [comment]
Thanks, just upgrade!
