### ISSUE TITLE
BUG TS: mkcert() plugin type mismatch

### ISSUE THREAD

**Issue by pwoloszun** [liuweiGL/vite-plugin-mkcert#44]
in package.json:
```
"typescript": "~4.8.3",
"vite": "~3.1.3",
"vite-plugin-mkcert": "~1.9.0",
```

in vite.config.ts:

```
import mkcert from 'vite-plugin-mkcert';

export default defineConfig({
  plugins: [
    mkcert()
  ]
});
```

throws TS error:

> _error TS2322: Type 'Plugin_2' is not assignable to type 'PluginOption'._

**Comment by liuweiGL** [comment]
Try reload your vscode

**Comment by pwoloszun** [comment]
> Try reload your vscode

Does not help.
What is more it **throws an error** when I **build** project.

> error TS2322: Type 'Plugin_2' is not assignable to type 'PluginOption'.

**Comment by pwoloszun** [comment]
Ofc **an ugly** _as any_ fixes it BUT it can be easily fixed in a good way. Just replace custom 'Plugin_2' with vites 'PluginOption' type.

Ugly fix:
```
import mkcert from 'vite-plugin-mkcert';

export default defineConfig({
  plugins: [
    mkcert() as any // ugly fix
  ]
});
```
