### ISSUE TITLE
v1.10.0 BUG on vite dev server start (works fine with v1.9.0)

### ISSUE THREAD

**Issue by pwoloszun** [liuweiGL/vite-plugin-mkcert#47]
It works fine with v1.9.0, BUT v1.10.0 throws this error:

```
error when starting dev server:
Error: Dynamic require of "fs" is not supported
    at file:///home/my-user/my-project/node_modules/vite-plugin-mkcert/dist/mkcert.mjs:13:9
```
My env info:
npx envinfo --system --npmPackages vite,vite-plugin-mkcert --binaries

```
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  npmPackages:
    vite: ~3.1.3 => 3.1.3 
    vite-plugin-mkcert: 1.10.0 => 1.10.0 
```

vite.config.ts:

```
import { defineConfig } from 'vite';
import mkcert from 'vite-plugin-mkcert';

export default defineConfig({
  server: {
    https: true,
  },

  plugins: [mkcert()]
});
```

**Comment by a2441918** [comment]
I get a different error.

The "path" argument must be of type string or an instance of URL. Received undefined


![image](https://user-images.githubusercontent.com/4927454/192286652-4faa3e63-82e1-452a-bcf5-ac9cad5ebe43.png)

**Comment by VincentLandais** [comment]
I am also facing this issue 

<img width="1728" alt="Screenshot 2022-09-27 at 11 13 42" src="https://user-images.githubusercontent.com/100678450/192485913-6a345e3b-352d-4967-a383-1291f88218eb.png">

**Comment by cafesao** [comment]
Same error here.

![image](https://user-images.githubusercontent.com/49770350/192598011-2a237e4f-66e7-455f-a1cf-2b84698d8a7a.png)

**Comment by moalamri** [comment]
Getting the same error, downgraded to v1.9.0 solved it

**Comment by liuweiGL** [comment]
close #45  close #46

**Comment by liuweiGL** [comment]
:handshake:
