### ISSUE TITLE
Error: Dynamic require of "fs" is not supported

### ISSUE THREAD

**Issue by Triazic** [liuweiGL/vite-plugin-mkcert#49]
My CI/CD pipelines which have worked until very recently have started throwing the following error:
![image](https://user-images.githubusercontent.com/38064196/192950731-31a5e394-90e2-4235-b209-2d82c3714005.png)

Any theory?

**Comment by liuweiGL** [comment]
Upgrade the plugin to lastest version

**Comment by liuweiGL** [comment]
#47
