### ISSUE TITLE
DOCS - Please update documentation [ path, cert name, sudo ]

### ISSUE THREAD

**Issue by n8sabes** [liuweiGL/vite-plugin-mkcert#55]
Very nice work on this -- thank you!

**SUGGESTIONS**
1. It is unclear where in the file system the cert files are created *(using the default configuration)*. Please add a reference in the documentation to `~/.vite-plugin-mkcert/certs`.

1. It is unclear the name of the cert added to the System Keychain. Please add reference in the documentation to `mkcert USER@HOST.lan` so it can be found and manually removed.

1. Advise the user in the documentation their `sudo` password is required to install the certs. Explain why.

These are merely suggestions as giving an unknown plugin sudo control is very concerning and would build trust.

**Comment by liuweiGL** [comment]
Thanks for your advice, the `sudo` privilege is required by [mkcert](https://github.com/FiloSottile/mkcert)

**Comment by n8sabes** [comment]
@liuweiGL, thank you.

I thought I searched the docs, but didn’t see the `certPath`, so I spent a few minutes searching directores so I could copy the cert/key to another non-vite backend api server that is proxied on a route — they both need the same cert/key.

*Just thought it would be of value to others users whom may be looking for the certs.*

**Comment by arxpoetica** [comment]
I would document the `sudo` stuff here. Yes, it's in mkcert, but I spent way too long trying to figure out why Kit was asking me to use sudo. Additionally, it's still not clear what's going on.

**Comment by turbobuilt** [comment]
I think there should be an option to disable sudo requirement.

**Comment by NOBLES5E** [comment]
There should be an option to disable the sudo requirement and avoid installing the certificate to the system. For many users, HTTPS certificate errors in the browser are acceptable.
