### ISSUE TITLE
Add certPath

### ISSUE THREAD

**Issue by n8sabes** [liuweiGL/vite-plugin-mkcert#56]
Adding a `certPath` would allow monorepos to share certs.

*Not all projects use `vite-plugin-mkcert` but is desirable to use the same cert.*

**Comment by liuweiGL** [comment]
I don't understand your intention, but if you already have a certificate, you don't need to use this plugin

**Comment by n8sabes** [comment]
For monorepos with multiple front-end projects and/or shared backend api / auth server, all should use the same cert in the specified secure directory. It would be nice to specify the target directory where the cert should be created and loaded from.

**Comment by liuweiGL** [comment]
The target directory is a constant, you can use it directly https://github.com/liuweiGL/vite-plugin-mkcert/blob/d49474d1595f52e7778df55c68c7ed4344fb5afc/plugin/lib/constant.ts#L8

**Comment by n8sabes** [comment]
Thank you @liuweiGL.

I coded certs manually for my monorepo this time, so there is no rush on this feature. `vite-plugin-mkcert` offers a lot of value for getting a project up quickly, and this would make it more useful.

If okay with you, I will leave this Issue open until the feature is added *(by you or me)*.

🙏
