### ISSUE TITLE
[Feature Request] Copy the rootCA file into the project's directory

### ISSUE THREAD

**Issue by evsar3** [liuweiGL/vite-plugin-mkcert#58]
First, congratulations! this is a great Vite Plugin and it's being very useful.

I would like to suggest that when the mkcert is initialized and the rootCA is generated, the `rootCA.crt` file could be could be copied into the project's root directory.
A disclaimer that the file must be gitignored can be used to warn the user that the file should not be pushed into the remote repository.

Another solution could be a custom command that could be invoked via `npx` and copy the rootCA file into the project 's directory.
Example:
```sh
npx vite-plugin-mkcert copy-ca
```

Thanks.

**Comment by evsar3** [comment]
Many times the development workflow requires that you install the CA in other devices. I couldn't find any API on the plugin that exposes the CA so it could be exported/copied.

The `mkcert -CAROOT` requires additional installation (at least on MacOS) where I had to install the `mkcert` via homebrew just to expose the CA location.

If the CA location is known by the plugin, an additional installation for `mkcert` should not be necessary.

Looking up for [devcert](https://github.com/davewasmer/devcert) used on my Express backend, it has something useful which is the the `getCABuffer` option that does something like what I'm suggestion.

**Comment by liuweiGL** [comment]
Now you can use the `savePath` parameter to customize the location, or find it [here](https://github.com/liuweiGL/vite-plugin-mkcert#savepath)

**Comment by jaulz** [comment]
This broke my existing setup because just suddenly uses a different root CA. Maybe this behaviour should only apply when the path is explicitly wet to "."?

**Comment by liuweiGL** [comment]
Sorry to cause you trouble, but this change should only make you reinstall the CA?

**Comment by liuweiGL** [comment]
Can you explain in detail the problem you are having,  i will submit a path if necessary.

**Comment by liuweiGL** [comment]
#59

**Comment by jaulz** [comment]
No worries, I still need to pin down the issue but suddenly my old root CA was not used anymore and since I shared it with another device it was not working there anymore. So I assume that suddenly a different root certificate was used after this change.
