### ISSUE TITLE
no such file or directory, scandir

### ISSUE THREAD

**Issue by yexianyao** [liuweiGL/vite-plugin-mkcert#62]
您好，我成功用yarn下载了项目所需依赖，如下图
![image](https://user-images.githubusercontent.com/48313330/219866467-934c714b-02a3-4704-919a-4cb070c9ad62.png)
但当我启动项目时，出现了如下错误：
![image](https://user-images.githubusercontent.com/48313330/219866508-c4af4d28-4987-428a-ad14-b7b235516d09.png)
根据所给的错误，我在它指出的路径中手动添加了.vite-plugin-mkcert文件，重新启动，错误变为
![image](https://user-images.githubusercontent.com/48313330/219866565-c6808795-b227-4817-9566-d460460dc75a.png)
查阅网上的解决办法，但并不适用。请问您有什么好的办法解决这个问题吗？

**Comment by JshGrn** [comment]
+1

**Comment by AlexZeitler** [comment]
> +1
> 
> EDIT: downgrade to 1.13.0 works

Same for me

**Comment by yexianyao** [comment]
> +1
> 
> EDIT: downgrade to 1.13.0 works

I downgrade the version from 1.13.1 to 1.13.0， and it works. Thank you very much
