### ISSUE TITLE
zsh: permission denied: ./mkcert

### ISSUE THREAD

**Issue by liuweiGL** [liuweiGL/vite-plugin-mkcert#7]
mac最新系统

_Originally posted by @0x219 in https://github.com/liuweiGL/vite-plugin-mkcert/discussions/6_

**Comment by 0x219** [comment]
![image](https://user-images.githubusercontent.com/50414099/124343389-9badce80-dbfd-11eb-9477-6beee0e89b50.png)
好像没用。。

**Comment by 0x219** [comment]
我来提pr把

**Comment by liuweiGL** [comment]
恩，可以呀。
