### ISSUE TITLE
Uninstall? All local traffic is now forwarded to HTTPS

### ISSUE THREAD

**Issue by bruceharrison1984** [liuweiGL/vite-plugin-mkcert#74]
### Describe the bug
I needed this briefly, now I no longer need it. I removed the package from the project, but all HTTP requests are still being forwarded to HTTPS, which now fails since I'm not using this package any longer.

### Reproduction

- Install and setup package
- Remove package
- Start dev server with `https: false`
- Local url forwards everything to HTTPS still and returns an SSL/TLS error
  - This includes all local traffic. So opening an entirely different project no longer works either. Effectively all HTTP traffic to local host is now redirected to HTTPS.

**Comment by liuweiGL** [comment]
Please clear your browser cache
