### ISSUE TITLE
火狐报错 SEC_ERROR_UNKNOWN_ISSUER

### ISSUE THREAD

**Issue by 863062879** [liuweiGL/vite-plugin-mkcert#75]
谷歌浏览器可以正常访问  火狐不行 报错因其证书颁发者未知、证书为自签名的，或者服务器未发送正确的中间证书。
插件版本1.16.0

**Comment by liuweiGL** [comment]
证书是 mkcert 生成的，得去上游仓库提 issue https://github.com/FiloSottile/mkcert
