### ISSUE TITLE
Running inside docker container

### ISSUE THREAD

**Issue by Shujee** [liuweiGL/vite-plugin-mkcert#78]
Is this plug-in supposed to work in a docker container too? 

1. How should my `vite.config.ts` look like? 
2. Also what port(s) should I map in my `docker-compose` file?
3. Is `server.hmr` option required/preferred in this scenario?

I have been struggling with it for several hours. In the best case scenario I was getting `NET::ERR_CERT_AUTHORITY_INVALID` in the browser when trying to access vite dev server.

In the current setup, I am:
1. Using `-- host` option with the `dev` script.
2. Running vite server on port 3000.
3. Mapping port 3000 to 3005 of the host machine in my `docker-compose file`

But I cannot access the Vite server in a host browser using any of `127.0.0.1`, `localhost` and `0.0.0.0`.

**Comment by liuweiGL** [comment]
I'm sorry, I'm not very familiar with Docker

**Comment by SomeoneIsWorking** [comment]
I don't know if this helps but on my docker-compose I had nginx and it was responsible for mapping vite dev to https

**Comment by liuweiGL** [comment]
This scenario is not possible because mkcert will only install the CA certificate in the docker container, which will cause the external host to fail to recognize the https certificate

**Comment by liuweiGL** [comment]
Maybe  you can use nginx as a reverse proxy and then use acme.sh to automatically create the certificate

**Comment by Shujee** [comment]
A year has passed since I had posted this question. Since then I have successfully devised a way of doing this using `vite-plugin-mkcert` package. If this helps someone, here is how I do it:

1. As part of your docker container startup (preferrably in `docker-entrypoint.sh`), after you have run `yarn` (or `npm install`), run the dev server (using `yarn dev` or `npm run dev`). 
2. This will generate the required certificate file in `/root/.vite-plugin-mkcert`. 
3. Wait for a few seconds to ensure that the certificate has been generated.
4. Copy the generated certificate (`rootCA.pem`) to your host machine, through a mount folder or whatever.
5. Rename this copied file on the host machine and change the extension from `.pem` to `.crt`.
6. Install the `.crt` file on the host machine.

You can now access your vite server running in the container from the browser on the host machine. Make sure you have mapped vite port (`3000` by default) to the same port number on the host machine. Also make sure you specify your host name in `vite.config.mts` in case you are using something other than `localhost`. Here is an example:

```
export default defineConfig({
  plugins: [
    mkcert({
      hosts: ['mylocalserver.test'],
    }),
    VueRouter({ ...
```
