### ISSUE TITLE
我在使用的时候遇到了 此网站无法提供安全连接localhost 发送的响应无效。 请问这个问题怎么解决

### ISSUE THREAD

**Issue by zcx992132258** [liuweiGL/vite-plugin-mkcert#88]
### Describe the bug
![image](https://github.com/liuweiGL/vite-plugin-mkcert/assets/54138798/cf4f3717-873a-461f-9b62-b6c66a6da62b)
我在使用了一段时间这个插件遇到了这个问题 请问怎么解决

### System Info

Output of `npx envinfo --system --npmPackages vite,vite-plugin-mkcert --binaries --browsers`:

```node

```

Used package manager: 

### Logs 

```node

```

---

**Comment by liuweiGL** [comment]
什么信息都没有怎么回答。。。

**Comment by zcx992132258** [comment]
> 什么信息都没有怎么回答。。。
![image](https://github.com/liuweiGL/vite-plugin-mkcert/assets/54138798/8370e7ff-c325-4755-891a-551099ed71eb)
我是这样配置的然后最近 https://localhost:8080/ 进入浏览器访问的时候无法访问了
![image](https://github.com/liuweiGL/vite-plugin-mkcert/assets/54138798/ece0a393-a1eb-46dd-a702-28bee75851f1)
我的vite版本是 5.2.7

**Comment by liuweiGL** [comment]
开启 debug 看看日志报错了没
