### ISSUE TITLE
Run in `configureServer`/`configurePreviewServer` hooks instead of `config` hook

### ISSUE THREAD

**Issue by benmccann** [liuweiGL/vite-plugin-mkcert#91]
### Describe the bug

The plugin shouldn't be invoked for things like building the production bundle or typechecking. Instead run it when we are using a server

### Reproduction

```
git clone git@github.com:benmccann/threlte.git
cd threlte/packages/xr
git checkout pnpm9
pnpm install
pnpm check
```

It asks for "Sudo password:" eventhough all I'm doing is invoking the type checker

### System Info

Used package manager: pnpm

**Comment by liuweiGL** [comment]
The plugin has specified the hook to run: https://github.com/liuweiGL/vite-plugin-mkcert/blob/e783eee14ccc4058fe7319c07a6d4673ddbb78b5/plugin/index.ts#L19C13-L19C18
