### ISSUE TITLE
Generate certificates from command line

### ISSUE THREAD

**Issue by Shujee** [liuweiGL/vite-plugin-mkcert#94]
Is there a way to use this plug-in from command-line? I don't want to run Vite server or do `yarn dev` etc. I just want those certificates to be generated in respective locations (`/root/.vite-plugin-mkcert/rootCA.pem` etc.). I need to do this from inside a script (`.sh`).

**Comment by liuweiGL** [comment]
Just use the https://github.com/FiloSottile/mkcert

**Comment by Shujee** [comment]
right, but how do I use those supply those certificates to this plug-in? If I generate them using `mkcert` and place them in `/root/.vite-plugin-mkcert/rootCA.pem`, will the plugin use those instead of generating new ones when I run dev server?

**Comment by liuweiGL** [comment]
This plug-in is for vite-server service, if you don't need vite-server why provide external certificate for the plug-in
