### ISSUE TITLE
HTTPS still works in production build even though vite-plugin-mkcert is a dev dependency

### ISSUE THREAD

**Issue by shlee9999** [liuweiGL/vite-plugin-mkcert#98]
### Describe the bug

HTTPS still works in production build even though vite-plugin-mkcert is installed as a dev dependency. This plugin should only affect the development environment, but it appears to influence the production build as well.

If this is not an intended behavior, it might be a potential security concern as development certificates should not be used in production environments.

### Reproduction

Steps to reproduce:
1. Install vite-plugin-mkcert as a dev dependency
```bash
npm install -D vite-plugin-mkcert
```

2. Configure vite.config.js
```javascript
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react-swc';
import mkcert from 'vite-plugin-mkcert';

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), mkcert()],
});

```

3. Build and run the production version
```bash
npm run build
npm run preview
```

Expected behavior: HTTPS should only work in development environment
Actual behavior: HTTPS continues to work in production build

### System Info

Output of `npx envinfo --system --npmPackages vite,vite-plugin-mkcert --binaries --browsers`:

```node
  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 4.82 GB / 15.91 GB
  Binaries:
    Node: 20.3.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.52)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vite: ^5.2.10 => 5.4.11 
    vite-plugin-mkcert: ^1.17.6 => 1.17.6 
```

Used package manager: npm

**Comment by liuweiGL** [comment]
```ts
export default defineConfig(({ command, mode, isSsrBuild, isPreview }) => {
  return {
    plugins: [react(), !isPreview&&mkcert()],
  }
})
```
